// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdbmswppXRnzhw5ggzMwnRrSiTHJ9J3o',
    appId: '1:801057253354:web:477faca3c26448758fb493',
    messagingSenderId: '801057253354',
    projectId: 'emlpoyform',
    authDomain: 'emlpoyform.firebaseapp.com',
    storageBucket: 'emlpoyform.firebasestorage.app',
    measurementId: 'G-RZMN3SVWDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCqaM7sw2NfTSZOvFCuu46QRsnMfJlSU',
    appId: '1:801057253354:android:4d24b197d94f11098fb493',
    messagingSenderId: '801057253354',
    projectId: 'emlpoyform',
    storageBucket: 'emlpoyform.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHdbmswppXRnzhw5ggzMwnRrSiTHJ9J3o',
    appId: '1:801057253354:web:3720e69f7be0aa778fb493',
    messagingSenderId: '801057253354',
    projectId: 'emlpoyform',
    authDomain: 'emlpoyform.firebaseapp.com',
    storageBucket: 'emlpoyform.firebasestorage.app',
    measurementId: 'G-MFSZWXG1GL',
  );

}